Update _config.yml
Update to fix the following error

Error: duplicated mapping key in "/vercel/path0/docs/_config.yml" at line 67, column 1:
    markdown: kramdown

Signed-off-by: sangramrath <sangram.rath@gmail.com>